quecome(liebre,zanahorias).
quecome(águila,liebre).
quecome(serpiente,liebre).
quecome(yaguareté,liebre).
quecome(comadreja,liebre).
quecome(ratón,plantas).
quecome(comadreja,ratón).
quecome(águila,ratón).
quecome(serpiente,ratón).
quecome(comadreja,langosta).
quecome(águila,comadreja).
quecome(serpiente,comadreja).
quecome(yaguareté,comadreja).
quecome(langosta,plantas).
quecome(mono,plantas).
quecome(hormiga,plantas).
quecome(mono,hormiga).
quecome(yaguareté,mono).
quecome(osohormiguero,hormiga).
quecome(yaguareté,osohormiguero).